clients:
  cronin-group3575.myshopify.com:
    access: 
      all_except: []
    menus: []
    carriers:
    - :aus_post
    - :red_pepper
    - :lifemap_science
    - :fabusa
  schumm-durgan-and-lang94.myshopify.com:
    access: 
      all_except: []
    menus: []
    carriers:
    - :aus_post
    - :fabusa
    - :red_pepper
    - :lifemap_science
  red-pepper.myshopify.com:
    access: 
      all_except: []
    menus: []
    carriers:
    - :aus_post
    - :red_pepper
  shop.redpepper.com:
    access: 
      all_except: []
    menus: []
    carriers:
      - :aus_post
      - :red_pepper
