clients:
  schumm-durgan-and-lang94.myshopify.com:
    access: 
      all_except: []
    menus: []
    carriers:
      - :aus_post
      - :fabusa
      - :aus_post_bus      
    service_host: shipping-staging.herokuapp.com
    local_host: localhost
  red-pepper.myshopify.com:
    access: 
      all_except: []
    menus: []
    carriers:
      - :aus_post
      - :red_pepper
    service_host: shipping-staging.herokuapp.com  
  shop.redpepper.com:
    access: 
      all_except: []
    menus: []
    carriers:
      - :aus_post
      - :red_pepper
    service_host: shipping-staging.herokuapp.com
  lifemap-bioreagents.myshopify.com:
    access: 
      all_except: []
    menus: []
    service_host: shipping-staging.herokuapp.com
    carriers:
    - :debug
    - :lifemap_science
