clients:
  default:
    menus: []
    access:
      all_except: []
    carriers:
      - :aus_post
      - :aus_post_bus  
    service_name: Webify Custom Shipping Calculator
    service_host: shipping.herokuapp.com
  schumm-durgan-and-lang94.myshopify.com:
    access: 
      all_except: []
    menus: []
    carriers:
      - :aus_post
      - :aus_post_bus      
      - :fabusa
      - :lifemap_science
      - :ridgewood      
    service_host: shipping-staging.herokuapp.com
  red-pepper.myshopify.com:
    access: 
      all_except: []
    menus: []
    carriers:
      - :aus_post
      - :red_pepper
    service_host: red-pepper-shipping.herokuapp.com
  shop.redpepper.com:
    access: 
      all_except: []
    menus: []
    carriers:
      - :aus_post
      - :red_pepper
    service_host: red-pepper-shipping.herokuapp.com
  shop.littleveggiepatchco.com.au:
    access:
      all_except: []
    menus: []
    carriers:
      - :aus_post
    service_host: shipping.webifytechnology.com
  littlevegpatch.myshopify.com:
    access: 
      all_except: []
    menus: []
    carriers:
      - :aus_post
    service_host: shipping.webifytechnology.com      
  lifemap-bioreagents.myshopify.com:
    access: 
      all_except: []
    menus: []
    carriers:
    - :debug
    - :lifemap_science
    service_host: shipping-lifemap-bioreagents.herokuapp.com
  bioreagents.lifemapsc.com:
    access: 
      all_except: []
    menus: []
    carriers:
    - :debug
    - :lifemap_science
    service_host: shipping-lifemap-bioreagents.herokuapp.com
  iconicbook.myshopify.com:
    access: 
      all_except: []
    menus: []
    carriers:
    - :ridgewood      
    service_host: shipping-ridgewood.herokuapp.com
  titika-active-wear.myshopify.com:
    access: 
      all_except: []
    menus: []
    carriers:
    - :purolator
    service_host: shipping-titika-active-wear.herokuapp.com
