clients:
  cronin-group3575.myshopify.com:
    access: 
      all_except: []
    menus: []
    carriers:
    - :aus_post
    - :red_pepper
    - :lifemap_science
    - :fabusa
    - :debug
  schumm-durgan-and-lang94.myshopify.com:
    access: 
      all_except: []
    menus: []
    carriers:
    - :aus_post
    - :fabusa
    - :red_pepper
    - :lifemap_science
    - :debug
    - :aus_post_bus
    service_host: localhost:3000
    local_host: localhost:3000
  aus-post-calculator-dev-shop.myshopify.com:
    access: 
      all_except: []
    menus: []
    carriers:
    - :aus_post
    - :fabusa
    - :red_pepper
    - :lifemap_science
    - :debug
    - :aus_post_bus
    - :chief_products
    service_host: localhost:3000
    local_host: localhost:3000
  red-pepper.myshopify.com:
    access: 
      all_except: []
    menus: []
    carriers:
      - :red_pepper
  www.foldaboxusa.com:
    access: 
      all_except: []
    menus: []
    carriers:
      - :fabusa
  shop.redpepper.com:
    access: 
      all_except: []
    menus: []
    carriers:
    - :aus_post
    - :red_pepper
  lifemap-bioreagents.myshopify.com:
    access: 
      all_except: []
    menus: []
    carriers:
    - :debug
    - :lifemap_science
