---
clients:
  schumm-durgan-and-lang94.myshopify.com:
    access:
      all_except: []
    menus: []
    carriers:
    - :aus_post
    - :fabusa
    - :debug
  red-pepper.myshopify.com:
    access:
      all_except: []
    menus: []
    carriers:
    - :aus_post
    - :red_pepper
    service_host: red-pepper-shipping.herokuapp.com
  shop.redpepper.com:
    access:
      all_except: []
    menus: []
    carriers:
    - :aus_post
    - :red_pepper
    service_host: red-pepper-shipping.herokuapp.com
  shop.littleveggiepatchco.com.au:
    access:
      all_except: []
    menus: []
    carriers:
    - :aus_post
  littlevegpatch.myshopify.com:
    access:
      all_except: []
    menus: []
    carriers:
    - :aus_post
  lifemap_science.myshopify.com:
    access:
      all_except: []
    menus: []
    carriers:
    - :lifemap_science
    service_host: webify-shipping.herokuapp.com
