---
clients:
  default:
    menus: 
    access:
      all_except: []
    carriers:
    - :aus_post
    - :aus_post_bus
  webifytechnology.myshopify.com:
    access:
      all_except: []
    menus: []
carriers:
  aus_post:
    public: true
    description: Australia Post
    service: false
    legacy_name: AusPost
  aus_post_bus:
    public: true
    description: Australia Post (with Shopify Real-time carrier shipping)
    service: true
    legacy_name: AusPostBus
  red_pepper:
    public: false
    description: Custom Rules - Red Pepper
    service: true
    service_discovery: false
  fabusa:
    public: false
    description: Custom Rules - FABUSA
    service: true
    service_discovery: false
    legacy_name: Private_FABUSA
  lifemap_science:
    public: false
    description: Custom Rules -- Lifemap Science
    service: true
    service_discovery: false
  chief_products:
    public: false
    description: Custom Rules -- Chief Products
    service: true
    service_discovery: false    
  debug:
    public: false
    description: Custom Rules -- Debug
    service: true
    service_discovery: false
  ridgewood:
    public: false
    description: Custom Rules -- Ridgewood
    service: true
    service_discovery: false    
    
